BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Skills] (
    [id] INT NOT NULL IDENTITY(1,1),
    [order] INT,
    [name] NVARCHAR(1000) NOT NULL CONSTRAINT [Skills_name_df] DEFAULT 'New Skill',
    CONSTRAINT [Skills_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
